TextTest will write diagnostics in /users/geoff/texttesttmp/texttestgeoff04Mar174057/TestSelf/DiagnosticHandling/TraceLevel based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application DIAG, checkout /nfs/vm/texttest/central_texttesttmp/texttestgeoff04Mar174057/TestSelf/DiagnosticHandling/TraceLevel/TargetApp/./
Running DIAG test-suite TargetApp
  Running DIAG test-case Test
Comparing differences for DIAG test-suite TargetApp
  Comparing differences for DIAG test-case Test (on output.diag)
  DIAG test-case Test FAILED : differences in output
  View details(v), Save(s) or continue(any other key)?
------------------ Differences in output --------------------
+ The trace level has been set to 9
<See also tkdiff window for details of output>
Faking start of external progam: 'tkdiff /nfs/vm/texttest/central_texttesttmp/texttestgeoff04Mar174057/TestSelf/DiagnosticHandling/TraceLevel/TargetApp/Test/output.diag /nfs/vm/texttest/central_texttesttmp/texttestgeoff04Mar174057/TestSelf/DiagnosticHandling/TraceLevel/TargetApp/diaggeoff04Mar174147/Test/output.diag'
  Save(s) or continue(any other key)?
