TextTest will write diagnostics in /users/geoff/texttesttmp/texttestgeoff17Jan11:33:30/unixConfig/CollateCore/UnreadableCore based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Using Application CORE, version fake, checkout /nfs/vm/texttest/central_texttesttmp/texttestgeoff17Jan11:33:30/unixConfig/CollateCore/UnreadableCore/TargetApp/./
Running CORE test-suite TargetApp
  Running CORE test-case DumpCore
Comparing differences for CORE test-suite TargetApp
  Comparing differences for CORE test-case DumpCore - SUCCESS! (on errors.core,output.core.fake)
  CORE test-case DumpCore CRASHED on ninilchik :
GDB backtrace command failed : Stack trace not produced for crash
Errors from GDB:
"/nfs/vm/texttest/central_texttesttmp/texttestgeoff17Jan11:33:30/unixConfig/CollateCore/UnreadableCore/TargetApp/core.fakegeoff17Jan11:33:49/DumpCore/stacktrace.core" is not a core dump: File format not recognized
No stack.

  View details(v), Save Version fake(1), Save(s) or continue(any other key)?
