<-CMD:ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 testnet-s16 mkdir -p ~/.texttest/tmp/console.19May181410.15727/system_under_test
<-CMD:rsync -e /usr/bin/ssh -azL /carm/proj/texttest-tmp/geoff/texttest.19May181217.16266/texttest/TestSelf/RunRemotely/DifferentFilesystems/UseRsync/TargetApp/hello.py testnet-s16:~/.texttest/tmp/console.19May181410.15727/system_under_test/hello.py
<-CMD:ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 testnet-s16 mkdir -p ~/.texttest/tmp/console.19May181410.15727/Test
<-CMD:cd /nfs/vm/texttest-tmp/geoff/texttest.19May181217.16266/texttest/TestSelf/RunRemotely/DifferentFilesystems/UseRsync/texttesttmp/console.19May181410.15727/hello/Test; ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 testnet-s16 cd ~/.texttest/tmp/console.19May181410.15727/Test ; env 'PATH="/carm/proj/texttest-tmp/geoff/texttest.19May181217.16266/texttest/TestSelf/RunRemotely/DifferentFilesystems/UseRsync/texttesttmp/console.19May181410.15727/hello/Test:${PATH}"' 'TEXTTEST_CHECKOUT=""' 'TEXTTEST_SANDBOX="/carm/proj/texttest-tmp/geoff/texttest.19May181217.16266/texttest/TestSelf/RunRemotely/DifferentFilesystems/UseRsync/texttesttmp/console.19May181410.15727/hello/Test"' python ~/.texttest/tmp/console.19May181410.15727/system_under_test/hello.py
->OUT:Hello World!
<-CMD:rsync -e /usr/bin/ssh -azL "testnet-s16:~/.texttest/tmp/console.19May181410.15727/Test/*" /carm/proj/texttest-tmp/geoff/texttest.19May181217.16266/texttest/TestSelf/RunRemotely/DifferentFilesystems/UseRsync/texttesttmp/console.19May181410.15727/hello/Test
->ERR:rsync: No match.
rsync: connection unexpectedly closed (0 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(463) [receiver=2.6.8]
->EXC:12
<-CMD:ssh -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=10 testnet-s16 rm -rf ~/.texttest/tmp/console.19May181410.15727
