<-PYT:datetime.datetime.now()
->RET:datetime.datetime(2014, 10, 15, 11, 57, 22, 36773)
<-PYT:import texttestlib.utils
<-PYT:texttestlib.utils.__path__
->RET:raise exceptions.AttributeError("'module' object has no attribute '__path__'")
<-PYT:texttestlib.utils.getUserName()
->RET:'fakeuser'
