<-PYT:time.no_such_method('argument', faking=True)
->RET:Exception: AttributeError("'module' object doesn't REALLY have an attribute 'no_such_method', stupid!")
<-PYT:urllib2.urlopen('http://no.such.site')
->RET:Exception: URLError Instance 'urlerror1'
<-PYT:urlerror1.__str__()
->RET:"<urlopen error (-2, 'No such site, you wally!')>"
<-PYT:urllib2.urlopen('http://another.no.such.site')
->RET:Exception: URLError Instance 'urlerror2'
<-PYT:urlerror2.__str__()
->RET:"<urlopen error (-2, 'Now you're really getting on my nerves!')>"
