TextTest will write diagnostics in /users/geoff/texttesttmp/texttest.15Jan170335/TestSelf/Miscellaneous/UnixOnly/KillFailsStartNew based on file at /users/geoff/work/master/Testing/Automatic/texttest/log4py.conf
Failed to connect to virtual server on stupid_machine1
A strange error occurred!

Unusable Xvfb process on machine stupid_machine1 owned by user fakeuser
Starting Xvfb on machine stupid_machine2
Tests will run with DISPLAY variable set to stupid_machine2:42.0
Using Application DISP
Running DISP test-suite TargetApp
  Running DISP test-case Test
Comparing differences for DISP test-suite TargetApp
  Comparing differences for DISP test-case Test (on errors.disp,output.disp)
  DISP test-case Test FAILED : differences in output
  View details(v), Save(s) or continue(any other key)?
------------------ Differences in output --------------------
1c1
< Display is stupid_machine1:42.0
---
> Display is stupid_machine2:42.0
  Save(s) or continue(any other key)?
