TextTest will write diagnostics in /users/claesv/texttesttmp/texttest.master.parisc_2_0claesv23Feb220011/TestSelf/CollateFiles/UnixOnly/Console/UnreadableCore based on file at /carm/proj/matador2/publish/master/Testing/Automatic/texttest/log4py.conf
Using Application CORE, version fake, checkout /users/claesv/texttesttmp/texttest.master.parisc_2_0claesv23Feb220011/TestSelf/CollateFiles/UnixOnly/Console/UnreadableCore/TargetApp/
Running CORE test-suite TargetApp
  Running CORE test-case DumpCore
Comparing differences for CORE test-suite TargetApp
  Comparing differences for CORE test-case DumpCore - SUCCESS! (on errors.core,output.core.fake)
  CORE test-case DumpCore CRASHED (unknown CRASH) :
  View details(v), Save Version fake(1), Save(s) or continue(any other key)?
GDB backtrace command failed : Stack trace not produced for crash
Errors from GDB:
"/users/claesv/texttesttmp/texttest.master.parisc_2_0claesv23Feb220011/TestSelf/CollateFiles/UnixOnly/Console/UnreadableCore/texttesttmp/core.fakeclaesv23Feb221751/DumpCore/stacktrace.core" is not a core dump: File format not recognized
coreCommands.gdb:1: Error in sourced command file:
No stack.
  Save Version fake(1), Save(s) or continue(any other key)?
